<?php
$I = new AcceptanceTester($scenario);
$I->wantTo('log in as regular user');
$I->amOnPage('/administrator/index.php');
$I->fillField("//*[@id='mod-login-username']", "admin");
$I->fillField("//*[@id='mod-login-password']", "admin");
$I->click('//*[@id=\'form-login\']/fieldset/div[3]/div/div/button');
$I->see('Users');
$I->wait(1);
$I->see('Extensions');
$I->wait(1);
$I->click('//*[@id=\'menu\']/li[5]/a/span');	
$I->moveMouseOver('//*[@id=\'menu\']/li[5]/ul/li[3]/a', 0, 0);
$I->click('//*[@id=\'menu-com-ijoomeradv\']/li[1]/a'); 
$I->click('//*[@id=\'adminForm\']/div[1]/table/tbody/tr/td[1]/table/tbody/tr/td[1]/a/img');
$I->moveback();
$I->click('.//*[@id=\'submenu\']/li[2]/a');
$I->wait(1);
$I->see('Extensions:[Manager]');
$I->moveback();
$I->click('.//*[@id=\'submenu\']/li[3]/a');
$I->wait(1);
$I->see('Configuration');
$I->moveback();
$I->click('.//*[@id=\'submenu\']/li[4]/a');
$I->wait(1);
$I->see('Menu Manager');
$I->moveback();
$I->click('.//*[@id=\'submenu\']/li[5]/a');
$I->wait(1);
$I->see('Push Notification');
$I->moveback();
$I->click('.//*[@id=\'submenu\']/li[6]/a');
$I->wait(1);
$I->see('Reports');
$I->moveback();
$I->wait(5);
?>