<?php
$I = new AcceptanceTester($scenario);
$I->wantTo('log in as regular user');
$I->amOnPage('/administrator/index.php');
$I->fillField("//*[@id='mod-login-username']", "admin");
$I->fillField("//*[@id='mod-login-password']", "admin");
$I->click('//*[@id=\'form-login\']/fieldset/div[3]/div/div/button');
$I->see('Users');
$I->wait(1);
$I->see('Extensions');
$I->wait(1);
$I->click('//*[@id=\'menu\']/li[5]/a/span');	
$I->moveMouseOver('//*[@id=\'menu\']/li[5]/ul/li[4]/a', 0, 0);
$I->click('//*[@id=\'menu-com-ijoomeradv\']/li[1]/a'); 
$I->click('//*[@id=\'adminForm\']/div[1]/table/tbody/tr/td[1]/table/tbody/tr/td[1]/a/img');
$I->moveback();
$I->click('.//*[@id=\'submenu\']/li[2]/a');
$I->waitForText('Extensions:[Manager]', 5);
$I->moveback();
$I->click('.//*[@id=\'submenu\']/li[3]/a');
$I->waitForText('Configuration', 5);
$I->moveback();
$I->click('.//*[@id=\'submenu\']/li[4]/a');
$I->waitForText('Menu Manager', 5);
$I->moveback();
$I->click('.//*[@id=\'submenu\']/li[5]/a');
$I->waitForText('Push Notification', 5);
$I->moveback();
$I->click('.//*[@id=\'submenu\']/li[6]/a');
$I->waitForText('Reports', 5);
$I->moveback();
